# -*- coding: utf-8 -*-
"""assigment_1biz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vntOCFvK4volbJNsTO1nT4ErDOfU9ev

Find the output of the following
Index
1.	If  name = ''' Hi How are you?
Starterd learning python.
It's really interesting.''' Then what is the output of following code
•	name[:]
•	name[-10:-5]
•	name[3:12]
•	name[12:3]
•	name[5,6]
•	name[-4:-12]
•	name[::2]
•	name[::-2]
"""

name='''Hi How are you?
Starterd learning python.
 It's really interesting.'''
name[:]
name[-10:-5]
name[3:12]
name[12:3]
#name[5,6]   #string indices must be integer

name[-4:-12]
name[-12:-4]
name[::2]
name[::-2]

"""2.	 L1 = [‘a’ , ‘b’, 20, 30, ‘t’, 100, 300, 400, ‘Happy’, ‘major’]
a.	L1[:]
b.	L1[::3]
c.	L1[::-2]
d.	How to extract  value “Happy” based on index and negative index
e.	How to check type of data in list at 4th position
f.	Extract values for 100, 300, 400


"""

l1 = ['a' , 'b', 20, 30, 't', 100, 300, 400, 'Happy', 'major']

l1[:]
l1[::3]
l1[::-2]

# extract happy based on index and negative index
l1[l1.index('Happy')] # based on index
l1[8]
l1[-2]

# check data type of data in list at 4th position
type(l1[3])
# extract 100 300 400
l1[5:8]

"""3.	If l2 =[1,2,3,5,[‘a’, ‘b’, ‘work hard’],100 , 200, “Success”] then what is the output of following
•	L2[4]
•	L2[1:5]
•	L2[7]
•	L2[7][2]
•	L7[7][2:]
•	L2[ : 3]
•	L2[3:]

"""

l2=[1,2,3,5,['a','b','work hard'],100,200,'Success']

l2[4]
l2[1:5]
l2[7]
l2[7][2]
l2[7][2:]
l2[:3]
l2[3:]

"""4.	From the above l2 value ‘b’ must be changed to ‘BEE’.
5.	From l2 “BEE” has to discard.
6.	In l2 add a dictionary at the end {‘insect’: [‘bee’, ‘moth’] , ‘bird’ : [‘parrot’, ‘sparrow’]}
7.	From l2 extract insect information.
8.	Create a dictionary d1 = {‘a’:10, ‘b’:20, ‘c’ : 30} and add the d1 at 2nd position of l2
9.	Based on new l2 created here extract the value 10 from l2 dictionary.
**bold text**
"""

#4
l2
l2[4][1]='BEE'
l2

#5
del l2[4][1]  # delete is usde
l2

#6
#l2.extend( [{'insect': ['bee', 'moth'] , 'bird' : ['parrot', 'sparrow']}])
l2
l2.pop()
l2

# 7 find insect info
l2
l2[8].get('insect')
l2[8]['insect']

#8
d1 = {'a':10, 'b':20, 'c' : 30}
# add
l2[1]=d1
l2.insert(10,d1)

l2

#9 Based on new l2 created here extract the value 10 from l2 dictionary.
l2[1].get('a')  # to fetch element from dictionary mention key

"""10.	If l2 =[1,2,3,5, (90,40,50,10), ‘Python’, 400 ,[‘a’, ‘b’, ‘work hard’],100 , 200, “Success”, (200,300, “Hundreds”)] then what is the output of following
•	L2[4][2]
•	L2[5][:]
•	L2[2] [:]
•	L2[1:5]
•	L2[5]
•	L2[5][3:-1]
•	L2[-1]
•	L2[-4, -3]
•	L2[-4: -10]
•	L2[7][2]
•	L7[-7][[2:]
•	L2[ :- 3]
•	L2[-3:]

"""

l2=[1,2,3,5, (90,40,50,10), 'Python', 400 ,['a', 'b', 'work hard'],100 , 200, 'Success', (200,300, 'Hundreds')]
l2

l2[4][2]
l2[5][:]
# l2[2][:]  'int' object is not subscriptable
l2[1:5]
l2[5]
l2[5][3:-1]
l2[-1]
l2[-4:-3]
l2[-4:-10]
l2[7][2]
l2[-7][2:]
l2[:-3]
l2[-3:]

"""11.	Ask user to enter the marks and define if the user got distinction, first class, second class, pass, Fails
If marks are more than 80 output must be “You got distinction”
For marks more than 60 output must be “You got First class”
Marks more than 40 will display “You got second class”
Marks more than or equal to 35 “PASS” Otherwise Fail


"""

marks=input('marks are') # taken input as names
if ( not marks.isalnum() and  not marks.isalpha()) or marks.isdigit():

  marks=float(marks)

  if marks >100 or marks <0:
    print(" invalid marks")
  elif marks >=80 and marks <=100:
     print('distinction')
  elif marks >=60:
     print('1st class')
  elif marks>=40:
     print('2nd class')
  elif marks >=35:
     print('pass')
  else:
     print('fail')


else:
  print('enter in right manner')

# usig function
marks=input("enter the marks: ")
def grade(marks):
  if ( not marks.isalnum() and  not marks.isalpha()) or marks.isdigit():
    marks=float(marks)
    if marks >100 or marks <0:
      return 'invalid marks'
    elif marks >=80 and marks <=100:
      return 'distinction'
    elif marks >=60:
      return '1st class'
    elif marks>=40:
      return '2nd class'  # if we use print instead we will be unable to call somewhere else
    elif marks >=35:
      return 'pass'
    else:
      return 'fail'


  else:
   return 'enter in right manner'

m=grade(marks)

# using function
marks=input("enter the marks: ")
def grade(marks):
  if ( not marks.isalnum() and  not marks.isalpha()) or marks.isdigit() or marks >100 or marks <0:
    return 'invalid marks'

  else:
    marks=float(marks)
    if marks >=80 and marks <=100:
      return 'distinction'
    elif marks >=60:
      return '1st class'
    elif marks>=40:
      return '2nd class'  # if we use print instead we will be unable to call somewhere else
    elif marks >=35:
      return 'pass'
    else:
      return 'fail'

grade(marks)

"""12.	Ask user to enter information about salary of the employee per year and rating received as A, B, C, D
If salary upto 5 lpa then increament based on ratings are  A = 16% , B=12%, C= 10%, D=6%
If salary upto 10 lpa then increament based on ratings are  A = 14% , B=10%, C= 8%, D=6%
If salary upto 15 lpa then increament based on ratings are  A = 8% , B=6%, C= 4%, D = no increment
If salary upto 23 lpa then increament based on ratings are  A = 7% , B=5%, C= 4%, D=no


"""

salary=input('salary is')
rating=input('rating is A/B/C/D :')


if salary.replace('.', '', 1).isdigit() and rating in 'abcdABCD':    #replace() is used here only for validation, not for modifying the original value.
  salary=float(salary)

  if salary <=500000.0:
    if rating.upper()=='A':
      print('salary increment by 16%',salary*1.16)
    elif rating.upper()=='B':
      print('salary increment by 12%',salary*1.12)
    elif rating.upper()=='C':
      print('salary increment by 10%',salary*1.10)
    elif rating.upper()=='D':
      print('salary increment by 6%',salary*1.06)


  elif salary <=1000000.0:
    if rating.upper()=='A':
      print('salary increment by 14%',salary*1.14)
    elif rating.upper()=='B':
      print('salary increment by 10%',salary*1.10)
    elif rating.upper()=='C':
      print('salary increment by 8%',salary*1.08)
    elif rating.upper()=='D':
      print('salary increment by 6%',salary*1.06)

  elif salary <=1500000.0:
    if rating.upper()=='A':
      print('salary increment by 8%',salary*1.08)
    elif rating.upper()=='B':
      print('salary increment by 6%',salary*1.06)
    elif rating.upper()=='C':
      print('salary increment by 4%',salary*1.04)
    elif rating.upper()=='D':
      print('salary increment by 0%',salary*1)

  elif salary <=2300000.0:
    if rating.upper()=='A':
      print('salary increment by 7%',salary*1.07)
    elif rating.upper()=='B':
      print('salary increment by 5%',salary*1.05)
    elif rating.upper()=='C':
      print('salary increment by 4%',salary*1.04)
    elif rating.upper()=='D':
      print('salary increment by 0%',salary*1)
  else:
      print("no increment")

else:
  print('invalid input')

"""Ask user to enter information about salary of the employee per year and rating received as A, B, C, D If salary upto 5 lpa then increament based on ratings are A = 16% , B=12%, C= 10%, D=6% If salary upto 10 lpa then increament based on ratings are A = 14% , B=10%, C= 8%, D=6% If salary upto 15 lpa then increament based on ratings are A = 8% , B=6%, C= 4%, D = no increment If salary upto 23 lpa then increament based on ratings are A = 7% , B=5%, C= 4%, D=no

"""



# using function
salary=input('enter your salary: ')
rating=input('eneter your rating A/B/C/D:  ').upper()
def total_sal(salary,rating):
  if salary.isdigit() and rating in 'ABCD':
    salary=float(salary)
    if salary<=500000:
      if rating=='A':
        output=salary*1.16
      elif rating=="B":
        output=salary*1.12
      elif rating=="C":
        output=salary*1.10
      elif rating=="D" :
        output=salary*1.06
    elif salary<=1000000:
      if rating=='A':
        output=salary*1.14
      elif rating=="B":
        output=salary*1.10
      elif rating=="C":
        output=salary*1.08
      elif rating=="D" :
        output=salary*1.06

    elif salary<=1500000:
      if rating=='A':
        output=salary*1.08
      elif rating=="B":
        output=salary*1.06
      elif rating=="C":
        output=salary*1.04
      elif rating=="D" :
        output=salary

    elif salary<23000000:
      if rating=='A':
        output=salary*1.07
      elif rating=="B":
        output=salary*1.05
      elif rating=="C":
        output=salary*1.04
      elif rating=="D" :
        output=salary
  else:
    return 'invalid entry'
  return output

total_sal(salary,rating)

"""13.	Ask user to opt for courses for master degree based on the following
L1 = [“HR”, “Finance”, “Marketing”, “DS”]
Based on above subject there are two different streams. For example- HR is having HR core and HR analytics and Marketing is having core and Marketing analytics. Analytics is the optional subject and having added extra fees. DS is not having analytics.
If fees for L1 is 2 lakhs for each course core subject having the same fees but analytics subject having 10% extra on 2 lakhs.
If student opts for hostel then 2 lakhs per year is added. For food monthly 2000 .
Transportation charges 13000 per semester. Calculate the total annual cost based on selected service.  
User will enter values as subject, analytics(Y/N), Hostel (Y/N), food(How many months?), Transportation(semester/annual)


"""

l1=['hr','finance','marketing','ds']
core_fees=200000
subject=input("subject name 'HR','finance','marketing','ds'):").lower()
is_analytics=input(' is analytic Y/N: ').upper()
is_hostel=input(' is hostel Y/N:').upper()
food=int(input('total month food taken'))
total_sem=int(input('total sem'))
total=0
if subject in l1 and is_analytics in ["Y", "N"] and is_hostel in ["Y", "N"]:
  total=core_fees
  if subject !='ds' and is_analytics=='Y':   # analystic not for ds
    total=total*1.10

  if is_hostel =="Y":   #  condiiton fro hostel
    total=total+200000

  total=total+(total_sem*13000)   # transporttion

  total= total + (food * 2000)   # food

  print('total annual fees',total)
else:
  print('invalid')

# using OOPs




class CollegeFees:

    def __init__(self, subject, is_analytics, is_hostel, food_months, total_sem):
        self.subject = subject.lower()
        self.is_analytics = is_analytics.upper()
        self.is_hostel = is_hostel.upper()
        self.food_months = food_months
        self.total_sem = total_sem

        self.core_fees = 200000
        self.allowed_subjects = ['hr', 'finance', 'marketing', 'ds']
    def is_valid(self):
        return (
            self.subject in self.allowed_subjects and
            self.is_analytics in ['Y', 'N'] and
            self.is_hostel in ['Y', 'N'])

    def calculate_fees(self):
        if not self.is_valid():
            print("Invalid input")
            return
        total = self.core_fees

        # analytics fee (not for ds)
        if self.subject != 'ds' and self.is_analytics == 'Y':
            total = total * 1.10
        # hostel fees
        if self.is_hostel == 'Y':
            total += 200000
        # transportation fees
        total += self.total_sem * 1300
        # food fees
        total += self.food_months * 2000
        print("Total annual fees:", int(total))

subject = input("Subject name (HR/Finance/Marketing/DS): ")
is_analytics = input("Is analytics (Y/N): ")
is_hostel = input("Is hostel (Y/N): ")
food = int(input("Total months food taken: "))
total_sem = int(input("Total semesters: "))

obj = CollegeFees(subject, is_analytics, is_hostel, food, total_sem)
obj.calculate_fees()


"""17.	Create a=100
•	Convert a to string
•	Convert a to list    
•	Convert a to tuple  
•	Convert a to dict
•	Convert a to set
•	Convert to float

"""

a=100

str(a) # str

# list(a)  # An int is not iterable, and list() only works on iterables (like strings, ranges, lists, tuples).
 list(str(a))

# tuple(a)  # 'int' object is not iterable

#dict(a)

a=100
#set(a)

float(a)  # coverted to float

"""8.	Create city = “Pune”
•	Convert to int     
•	Convert float
•	Convert list  
•	Convert tuple
•	Convert dict
•	Convert set
•	Obsert errors and note it down for all conversions

"""

city='pune'

#convert to int
int(city)  #invalid literal for int() with base 10: 'pune'

#convert float
#float(city) #could not convert string to float: 'pune'

# convert to list
list(city)

tuple(city)

dict(city) # dictionary update sequence element #0 has length 1; 2 is required

#set\
set(city)

"""14.	Digitalize the book allotment process for school. Charges are mentioned here in the given table:"""

books={'Hindi':{'1-4':60,'5-8':100,'9-10':150},
       'Marathi':{'1-4':60,'5-8':100,'9-10':150},
       'English':{'1-4':80,'5-8':100,'9-10':150},
       'Science':{'1-4':90,'5-8':120,'9-10':200},
       'Maths':{'1-4':100,'5-8':140,'9-10':250}}

notebooks={'square':{100:40,200:70},'4lines':{100:30,200:50},
           'two_lines':{100:30,200:50},
           'single line':{100:60,200:100},
           'a4':{100:100,200:180}}

# notebooks['square']

total=0
buy_book=input('do you want to buy a book Y/N').upper()
if buy_book=='Y':
  subject=input('whcih subject book(Hindi/Marathi/English/Science/Maths) :').capitalize()
  std=input('whcih standard 1-4/5-8/9-10 :')

  if subject in books and std in books[subject]:
    price=books[subject][std]
    total=total+price
    print('books price:',total)
  else:
    print('invalid input')
buy_notebook=input('want to buy notebook Y/N:').upper()
if buy_notebook=='Y':
  notebook_name=input('whcih notebook (square,2line,single line,A4) :').lower()
  pages=int(input('pages want 100/200 :'))

  if notebook_name in notebooks and pages in notebooks[notebook_name]:
    prices=notebooks[notebook_name][pages]
    total=total+prices
    print('notebooks price:',prices)
  else:
    print('invalid input')

print("Total amount to pay =", total)

"""List operations
10.	Create the empty list snames
•	 Add value 20 in the list using append
•	 Add value 30 in the list using extend
•	Add values in the list using append
•	Add value “WORK" in the list using extend
•	 Create a new list combo having the values [1, ‘a’, ‘b’ ,2 , 3]
•	Add sname to combo using addition operator
•	Add combo to snames using append
•	Add combo to snames using extend.

"""

snames=[] # empty list

#add name
snames.append(30)

#snames.extend(30) #'int' object is not iterable

snames.extend([30])

# append values  #'int' object is not iterable

#
#snames.append(30,40,'a') #'int' object is not iterable

snames.extend('Work') # extend Work
snames

#
snames1=[1, 'a', 'b' ,2 , 3]
snames+snames1

snames.append(snames1)

snames.extend(snames1)

snames



"""13.i want to make digitlizes book and notebook billing print system
workfow
1.  function1-Take input- that is ask user to whcih books he wnat to buy or whcih notebook he wants to buy .make dictionary of that order

2. function -2  calculate overall bill

3.  function_3 print bill
"""

books={'Hindi':{'1-4':60,'5-8':100,'9-10':150},
       'Marathi':{'1-4':60,'5-8':100,'9-10':150},
       'English':{'1-4':80,'5-8':100,'9-10':150},
       'Science':{'1-4':90,'5-8':120,'9-10':200},
       'Maths':{'1-4':100,'5-8':140,'9-10':250}}

notebooks={'Square':{100:40,200:70},'four_lines':{100:30,200:50},
           'Two_lines':{100:30,200:50},
           'ingle line':{100:60,200:100},
           'a4':{100:100,200:180}}

print('Welcome to Abhi\'s shop')

#########Part1#############
def take_order():
  book_order={}
  notebook_order={}

  while True:
    choice=input('want to buy book? (Y/N) :  ').upper()

    if choice=='N':
      break
    subject=input("Book name Hindi/Marathi/English/Science/Maths) : ").capitalize()
    std=input('which std (1-4 / 5-8 / 9-10) :  ')
    qty=int(input('how many books you want?:  '))

    if subject in books and std in books[subject]:
      book_order[subject]={'qty':qty,'std':std}
    else:
      print('no this book is not avialable')

  while True:
     choice=input('want to buy Notebook? (Y/N) :  ').upper()

     if choice=='N':
       break
     nb_type=input("Notebook Type name Square/Two_lines//Four_lines/Single_line/a4) : ").capitalize()
     pages=int(input('How many pages do you want 100/200) :  '))
     qty=int(input('how many notebooks you want?:  '))

     if nb_type in notebooks and pages in notebooks[nb_type]:
      notebook_order[nb_type]={'qty':qty,'pages':pages}
     else:
      print('no this notebook is not avialable')




  print("\nBOOK ORDER:", book_order)
  print("NOTEBOOK ORDER:", notebook_order)

  return book_order, notebook_order

####2nd part

def calculate_bill(book_order, notebook_order):
    total = 0

    # Book bill
    for book, details in book_order.items():
        price = books[book][details['std']]
        total += price * details['qty']

    # Notebook bill
    for nb, details in notebook_order.items():
        price = notebooks[nb][details['pages']]
        total += price * details['qty']

    return total
### 3 part
def print_bill(book_order, notebook_order, total):
    print("\n------- BILL -------")

    if book_order:
        print("\nBooks:")
        for book, d in book_order.items():
            price = books[book][d['std']]
            print(f"{book} | Std {d['std']} | Qty {d['qty']} | Rs {price * d['qty']}")

    if notebook_order:
        print("\nNotebooks:")
        for nb, d in notebook_order.items():
            price = notebooks[nb][d['pages']]
            print(f"{nb} | {d['pages']} pages | Qty {d['qty']} | Rs {price * d['qty']}")

    print("\nTotal Amount: Rs", total)
    print("--------------------")

book_order, notebook_order = take_order()
total_amount = calculate_bill(book_order, notebook_order)
print_bill(book_order, notebook_order, total_amount)


"""11.	Create one list l1 having two elements and l3 having 7 elements. Now at 4th position add l1"""

l1=[1,2]
l3=[1,2,3,4,'a','b','c']
l3[3]=l1

l3

"""12.	Collection is the list having values [1,2,3,[‘a’, ‘b’, ‘c’], 100, ‘Nisha’, 20.50, 90.10 ] if the data is in integer or float then multiply with 5.  
•	From the collection delete the record for “Nisha”
•	Find the location of 20.50

"""

lst=[1,2,3,['a','b','c'],100,'Nisha',20.50,90.10]
lst1=[]
for i in lst:
  print(type(i))
  if type(i)==int or type(i)==float:
    lst1.append(i * 5)
  else:
    lst1.append(i)
lst1

#remove nisha
lst.remove('Nisha')

# location of 20.50]
lst.index(20.50)

"""13.	Create a comprehensive list for square upto 10
14.	Create the comprehensive list to find number divisible by 13 till 200
15.	Create the list which is divisible by 4 from 300 to 400  

"""

sq_100=[ i**2 for i in range(1,11)]
sq_100

No_div_13=[ i  for i in range(1,201) if i%13==0 ]
No_div_13

No_div_4=[ i  for i in range(300,401) if i%4==0 ]
No_div_4

"""16.	Create a comprehensive list to generate list up to x, y as a number. For example if x = 3 list will be x_list = [0,1,2] and y=2 then y_list =[0,1]
Then generate a new list based on all combination of x and y.
For example: if x = 1 and y =2  then x_list = [0] and y_list = [0,1]
And output will be [[0,0],[0,1]]

If x=2 and y = 2 then output will be [[0,0],[0,1][1,0],[1,1]]

"""

n=3
m=2
x_list=[i for i in range(1,n+1)]
y_list=[i for i in range(1,m+1)]
xy_list=[[i,j] for i in range(1,n+1) for j in range(1,m+1)]
print(x_list)
print(y_list)
print(xy_list)

"""What is the difference between add and update methods in set?
18.	What is the difference between append and extend methods in list?
19.	What is the difference between pop and remove methods?
20.	What is the difference between discard, pop, remove methods?
21.	How to create empty set?

add() adds one element to the set.

update() adds multiple elements at the same time.


append() adds one item at the end.

extend() adds all items from another list.

append() makes list inside list, extend() does not.

pop() removes item using index and returns it.

remove() removes item using value.

remove() gives error if value not found.

discard() removes value and no error if not present.

remove() removes value but gives error if not present.

pop() removes and returns an element.

{} creates empty dictionary, not set.
"""

s = {1, 2}

s.add(3)
print(s)

s.update([4, 5])
print(s)

l = [1, 2]

l.append([3, 4]) # add list as elemenet
print(l)

l = [1, 2]
l.extend([3, 4])  # extends list
print(l)

l = [10, 20, 30]

l.pop(1)  # by index
print(l)

l.remove(30)  # by element
print(l)

s = {1, 2, 3}

s.discard(4)      # No error

# s.remove(4)     #  KeyError


s.remove(1)
s.pop()          # Removes random element
print(s)

s = set()
print(type(s))

"""22.	Create the set s1 and s2 and perform set operations like union, intersection, difference, set difference.
23.	Create l2 as a list and perform set operation on s1 with l1

"""

#22
s1 = {1, 2, 3, 4}
s2 = {3, 4, 5, 6}

s1.union(s2) # union
s1.intersection(s2) # intersection
s1.difference(s2)  # diffre
print(s1 | s2)   # Union
print(s1 & s2)   # Intersection
print(s1 - s2)   # Difference
print(s2 - s1)   # Set difference

#23 set operation not directly done on list
s1 = [1, 2, 3, 4]
s2 = [3, 4, 5, 6]
print(list(set(s1) | set(s2)))   # Union
print(list(set(s1) & set(s2)))   # Intersection
print(list(set(s1) - set(s2)))   # Difference

"""24.	Ask user to enter the name and DOB and generate the password based on first name 4 characters and  @ddmm. For example name = SURESH and DOB = 05-05-1978 then password will be SURE@0505"""

name=input('enter a name:  ').upper()
dob=input('enter dob(dd-mm-yyyy):   ')
if len(name) < 4:
    print("Name must have at least 4 characters")
else:
    password = name[:4].upper() + '@' + dob[:2] + dob[3:5]
    print(password)



"""25.	Ask user to enter the name and DOB and generate the password based on first name 4 characters and  last 4 digits of DOB or year @yyyy. For example name = SURESH and DOB = 05-05-1978 then password will be SURE@1978"""

name=input('enter a name:  ').upper()
dob=input('enter dob(dd-mm-yyyy):   ')
if len(name) < 4 or len(dob)<10:
    print("Name must have at least 4 characters")
else:
    password = name[:4].upper() + '@' + dob[-4:]
    print(password)

"""26.	Create the format mentioned here.
*
* *
* * *
* * * *

"""

for i in range(1,5):
  for j in range(i):
    print('*',end=" ")
  print()

for i in range(4, 0, -1):
    for j in range(i):
        print("*", end=" ")
    print()

"""28.	Str_val = “ABCD” then create the format as mentioned below:
A
A B
A B C
A B C D
29.	Create the format mentioned below:
A
BB
CCC
DDDD

"""

Str_val = "ABCD"

for i in range(1, len(Str_val) + 1):
    for j in range(i):
        print(Str_val[j], end=" ")
    print()

Str_val = "ABCD"
re=''
for ch in Str_val:
  re=re+ch+' '
  print(re)  # or print(' '.join(re))

#30
Str_val = "ABCD"

for i in range(len(Str_val)):
    print(Str_val[i] * (i + 1))
print()

#31
for i in range(1, 5):
    print(str(i) * i)

Val = "ABCD"


result = ""          # empty string

for ch in Val[::-1]:
    result = result + ch
    print(result)

val='ABCD'
result=''
for i in val:
  result=result+i
  print(result)

val="UPGRAD"
result=''
for i in val[::-1]:
  result=result+i
  print(result)

val=input("the name is : ")
def func(val):
  result=''
  for i in val[::-1]:
    result=result+i
    print(result)
func(val)

"""33.	Create a list of odd numbers from 1 to 10
1.	Using for loop
2.	Using comprehensive list

"""

lst=[]
for i in range(1,11):
  if i%2!=0:
    lst.append(i)
print(lst)

lst=[i for i in range(1,11) if i%2!=0]
lst

"""34.	Create even number list using for loop from 200 to 250"""

lst=[]
for i in range(200,251):
  if i%2==0:
    lst.append(i)
print(lst)

from itertools import count
lst=[]
for i in count(199,1):
  if i>250:
    break
  if i%2==0 :
    lst.append(i)
print(lst)

"""35.	List2 = [2,70,'work', para, 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3,10,302.5]
Multiply each and every element by 2 and display the answer


"""

List2 = [2, 70, 'work', 'para', 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3, 10, 302.5]

result = []

for item in List2:
    if isinstance(item, (int, float, str, list, tuple)):
        result.append(item * 2)

    elif isinstance(item, set):
        set1=set()
        for i in item:
          set1.add(i*2)
        result.append(set1)   # set * 2 not allowed

    elif isinstance(item, dict):
        new_dict = {}
        for i, j in item.items():
            new_dict[i * 2] = j*2
        result.append(new_dict)

print(result)
print(set1)

"""36.	List2 = [2,70,'work', para, 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3,10,302.5]    multiply each item by 5

"""

list2=[]
list1 = [2, 70, 'work', 'para', 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3, 10, 302.5]
for item in list1:
    if isinstance(item, (int, float, str,tuple)):
        list2.append(item * 5)

    elif isinstance(item, list):
        lst=[]
        for i in item:
          lst.append(i*5)
        list2.append(lst)

    elif isinstance(item, set):
        set1=set()
        for i in item:
          set1.add(i*5)
        list2.append(set1)   # set * 2 not allowed

    elif isinstance(item, dict):
        new_dict = {}
        for i, j in item.items():
            new_dict[i * 5] = j
        list2.append(new_dict)

list2

"""38.	Create a function to validate user first name/last name. User first name/last name should contain only characters. No special characters, numbers, space in name"""

f_name=input("enetr 1st name: ").capitalize()
l_name=input("enter lastname: ").capitalize()

def valid_name(f_name,l_name):

  if f_name.isalpha() and l_name.isalpha():
    return f_name,l_name
  else:
    return "invalid"

valid_name(f_name,l_name)

"""39.	Create a function to accept mobile number. Mobile number should contain 10 digits. No Special character, alphabets and space."""

mob=input('enter a number:  ')
def valid_Mob(number):
  if number.isdecimal() and len(number)==10:
    number=int(number)
    return number
  else:
    return 'invalid number'
valid_Mob(mob)

"""40.	Create a function to generate auto-password based on specific person details. Ask user to enter name, DOB. And password must be First name 4 characters and year of birth."""

name=input('enter a name:  ').capitalize()
dob=input('enter dob(dd-mm-yyyy):   ')
def password(name,dob):
  if len(name) < 4 or len(dob)<10 or not name.isalpha() :
      return "Name must have in proper format"
  else:
      password = name[:4].upper() + '@' + dob[-4:]
      return password
password(name,dob)

"""41.	Create a empty dictionary and ask user to enter values as name, DOB, mobile number add all the details in dictionary with customer number as 1 for first time. If user try to enter another value, then number should increase as 2 with new details and previous values should not change.
For example:
{}
{1:{name : "Sachin", "DOB": "21-06-1965" , "mobile": "1234123423"}}

{1:{name : "Sachine", "DOB": "21-06-1965" , "mobile": "1234123423"},
2: {name : "Sumedh", "DOB": "02-02-2002" , "mobile": "1234123433"}}

"""

def create_dict():
  global dict1
  dict1={}
  id=1
  while True:
    name=input("the name is: ")
    if name.isalpha()==False:
      print("invalid")
      continue
    dob=input("the date of birth is dd-mm-yyyy:  ")
    mobile=input("the mobile no should be")
    if not len(mobile)==10 or not mobile.isdigit():
      print('mobile no should be 10 digits or must be in digts')
      continue
    entry=input("do you want to make entry Y/N: ").upper()
    if entry not in 'YN':
      print("enter properly as Y or N")
      continue


    dict1[id]={'name':name,'dob':dob,'mobile':mobile}
    id=id+1
    if entry=='N':
      break


  return dict1



create_dict()
print(dict1)

45.	Dict1= {“Key”: {“subkey”:20} ,  “k2”:{“sub2” : 5}, “k3” : {“sub4” :16},  “k4” : {“sub4” : 6}}
Sort elements based on values
Output must be {,  “k2”:{“sub2” : 5}, “k4” : {“sub4” : 6},  “k3” : {“sub4” : 16}, “Key”:{“subkey”:20}}



###46
def val_mobile(mobile):
  if mobile.isdigit() and len(mobile)==10:
    val=mobile
    flag=True
  else:
    val="error"
    flag=False
  return val,flag

def accept_input():
  name=input('enter the name: ')
  mobile=input('enter mobile: ')

  return name,mobile

input_val=accept_input()

val_mobile('9168135918')

input_val

input_val[1]




#46.	Create a function to calculate age till now.
from datetime import date
def cal_age(dob):
  today=date.today()
  age=today.year-dob.year
  #if (today.month, today.day) < (dob.month, dob.day):
        #age -= 1

  return age
    
#47.	Create a function to check age eligibility for given customer based on DOB. Function will take two input DOB and ELIGIBILITY age.    
    

from datetime import date

dob = date(2000, 12, 15)
print(cal_age(dob))

from datetime import date, datetime

def is_eligible(dob_str):

    dob = datetime.strptime(dob_str, "%Y-%m-%d").date()
    today = date.today()
    age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
    return age >= 18

print(is_eligible("2009-02-10"))  # False (not yet 18)
print(is_eligible("2000-12-15"))  # True (over 18)
"""

48.calculate ttoal hrs based on input sign in and sign out time
"""

from datetime import datetime

def total_hours(sign_in, sign_out):
    fmt = "%H:%M"  #format
    global in_time,out_time
    in_time = datetime.strptime(sign_in, fmt)
    out_time = datetime.strptime(sign_out, fmt)
    hours = (out_time - in_time).seconds / 3600
    return hours

print(total_hours("09:30", "17:45"))  # 8.25
print(total_hours("08:15", "16:30"))  # 8.25

print(out_time-in_time)

"""#55 .	Build a function to print bill. Generate the bill as mentioned below."""

hotel = "Welcome Hotel name"
sr = 1
menu = "idli"
qty = 2
price = 60
total = qty * price
print("-" * 55)
print("|{:^53}|".format(hotel))
print("-" * 55)
print("|{:^5}{:^20}{:^10}{:>18}|".format("sr", "Menu", "qunt", "price"))
print("|{:^5}{:^20}{:^10}{:>18}|".format(sr, menu, qty, price))
print("|" + " " * 53 + "|")
print("-" * 55)
print("|{:^35}{:>18}|".format("Total", total))
print("-" * 55)

"""#assignment1"""

hotel = "Welcome Hotel name"
sr = 1
menu = "idli"
qty = 2
price = 60
total = qty * price

file_path = "/content/bill.txt"

with open(file_path, "w") as f:
    f.write("-" * 55 + "\n")
    f.write("|{:^53}|\n".format(hotel))
    f.write("-" * 55 + "\n")

    f.write("|{:^5}{:^20}{:^10}{:>18}|\n".format("sr", "Menu", "qunt", "price"))
    f.write("|{:^5}{:^20}{:^10}{:>18}|\n".format(sr, menu, qty, price))

    f.write("|" + " " * 53 + "|\n")
    f.write("-" * 55 + "\n")

    f.write("|{:^35}{:>18}|\n".format("Total", total))
    f.write("-" * 55 + "\n")

print("Bill saved successfully in bill.txt")
with open(file_path,"a") as f:
  f.write("\n bill printed successfully")

"""2nd assignment"""

# copy, move, copytree
import os
def fn():
    path="C:\\Users\\Aditya\\OneDrive\\Desktop\\INTERNSHIP\\PYTHON"

    for i in os.listdir(path):
        file_name = path +"/"+ i
        # print(file_name)
        d=os.stat(file_name).st_size/1024
        # print (file_name,d, "KB")

        if d<10:
          print("Small size files",file_name, d)
        if d<20:
           print("Medium size Files",file_name, d)
        if d>20:
           print("Large files", file_name, d)
fn()
 #2.To rename files

"""15.15.	Create an interest bucket for Fix Deposit in the bank. Ask user to enter start date and end date for the FD and check which bucket list it belongs to and assign the interest rate"""

from datetime import datetime

def fd_interest_bucket(start_date, end_date):
    days = (end_date - start_date).days

    if days < 7:
        return "FD duration too short", None

    if 7 <= days <= 45:
        return "7 to 45 days", 5.75
    elif 46 <= days <= 179:
        return "46 to 179 days", 6.25
    elif 180 <= days <= 210:
        return "180 to 210 days", 6.35
    elif 211 <= days < 365:
        return "211 days to less than 1 year", 6.40
    elif 365 <= days < 730:
        return "1 year to less than 2 years", 7.00
    elif 730 <= days < 1095:
        return "2 years to less than 3 years", 6.75
    elif 1095 <= days < 1825:
        return "3 years to less than 5 years", 6.70
    else:
        return "5 years and above", 6.60


start = input("Enter FD start date (YYYY-MM-DD): ")
end = input("Enter FD end date (YYYY-MM-DD): ")

start_date = datetime.strptime(start, "%Y-%m-%d")
end_date = datetime.strptime(end, "%Y-%m-%d")

bucket, rate = fd_interest_bucket(start_date, end_date)

print("\nFD Duration (days):", (end_date - start_date).days)
print("Interest Bucket:", bucket)
print("Interest Rate:", rate, "%")

from datetime import datetime

class BankFD():

    def __init__(self, start_date, end_date):
        self.start_date = start_date
        self.end_date = end_date
        self.days = 0
        self.bucket = ""
        self.rate = None
    def get_days(self):
        self.days = (self.end_date - self.start_date).days

    def get_bucket_and_rate(self):
      if self.days < 7:
        self.bucket = "FD duration too short"
        self.rate = None
      elif 7 <= self.days <= 45:
        self.bucket = "7 to 45 days"
        self.rate = 5.75
      elif 46 <= self.days <= 179:
        self.bucket = "46 to 179 days"
        self.rate = 6.25
      elif 180 <= self.days <= 210:
        self.bucket = "180 to 210 days"
        self.rate = 6.35
      elif 211 <= self.days < 365:
        self.bucket = "211 days to less than 1 year"
        self.rate = 6.40
      elif 365 <= self.days < 730:
        self.bucket = "1 year to less than 2 years"
        self.rate = 7.00
      elif 730 <= self.days < 1095:
        self.bucket = "2 years to less than 3 years"
        self.rate = 6.75
      elif 1095 <= self.days < 1825:
        self.bucket = "3 years to less than 5 years"
        self.rate = 6.70
      else:
        self.bucket = "5 years and above"
        self.rate = 6.60

    def show_details(self):
        self.get_days()
        self.get_bucket_and_rate()
        print("FD Duration (days):", self.days)
        print("Interest Bucket:", self.bucket)
        print("Interest Rate:", self.rate)



start = input("Enter FD start date (YYYY-MM-DD): ")
end = input("Enter FD end date (YYYY-MM-DD): ")

start_date = datetime.strptime(start, "%Y-%m-%d")
end_date = datetime.strptime(end, "%Y-%m-%d")

fd = BankFD(start_date, end_date)
fd.show_details()

print('hello')



"""49.	Create a function to generate a Fibonacci Series. 0 1 1 2 3 5 8 13 21"""

def fib():
    a = 0
    b = 1
    while a <= 100:
        print(a, end=" ")
        c = a + b
        a = b
        b = c

fib()
print()

"""50.	Write a code to generate factorial of the number  For example: factorial of 5 = 5! = 5*4*3*2*1

"""

def fact(n):
    f = 1
    for i in range(1, n + 1):
        f = f * i
    print(f)

fact(5)

"""51.	Write a program to find largest number in the list.

"""

lst = [10, 45, 23, 89, 12]
max = lst[0]
for i in lst:
    if i > max:
        max = i
print(max)

"""52.	Write a program to check frequency of each element in the list.

"""

lst = [1, 2, 2, 3, 4, 1, 2]
d = {}
for i in lst:
    if i in d:
        d[i] = d[i] + 1
    else:
        d[i] = 1
print(d)

"""53.	There are two string l1 =[ 1,2,3,4,5] and l2 =[3,2,8,7,9] then write a program to find common elements in the list.

"""

l1 = [1, 2, 3, 4, 5]
l2 = [3, 2, 8, 7, 9]
l3 = []
for i in l1:
    if i in l2:
        l3.append(i)
print(l3)

