# -*- coding: utf-8 -*-
"""Biz assigne 21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmCTTOBJGSONX-yrGsSr9-A_J38OIhcN
"""

# ---------------- LIST COMPREHENSION ----------------

# 1. Squares of numbers from 1 to 10
sq = [i*i for i in range(1, 11)]
print(sq)

# 2. Even numbers between 1 and 50
even = [i for i in range(1, 51) if i % 2 == 0]
print(even)

# 3. Convert strings to uppercase
names = ["abhi", "ram", "sham"]
up = [i.upper() for i in names]
print(up)

# 4. Only positive numbers
nums = [-3, 5, -1, 7, 0, 9]
pos = [i for i in nums if i > 0]
print(pos)

# 5. Tuples (num, num^2) from 1 to 5
tup = [(i, i*i) for i in range(1, 6)]
print(tup)

# 6. Extract vowels from string
s = "education"
v = [i for i in s if i in "aeiouAEIOU"]
print(v)

# 7. Flatten 2D list
lst = [[1, 2], [3, 4], [5, 6]]
flat = [j for i in lst for j in i]
print(flat)

# 8. Replace negative numbers with 0
nums = [-2, 4, -5, 6]
new = [0 if i < 0 else i for i in nums]
print(new)

# 9. Length of each word
words = ["python", "java", "c"]
lengths = [len(i) for i in words]
print(lengths)

# 10. Words not starting with A or a
words = ["Apple", "ball", "ant", "cat"]
res = [i for i in words if not i.lower().startswith('a')]
print(res)

# 11. Even or odd list
nums = [1, 2, 3, 4]
eo = ["even" if i % 2 == 0 else "odd" for i in nums]
print(eo)

# 12. Numbers divisible by 3 and 5 (1–100)
d35 = [i for i in range(1, 101) if i % 3 == 0 and i % 5 == 0]
print(d35)

# 13. Multiplication table 1–5
table = [[i*j for j in range(1, 6)] for i in range(1, 6)]
print(table)

# 14. Dictionary keys to list
d = {"a": 1, "b": 2}
keys = [i for i in d]
print(keys)

# 15. Digits from string
s = "ab12cd34"
digits = [i for i in s if i.isdigit()]
print(digits)

# 16. Remove spaces from string
s = "hello world"
nospace = [i for i in s if i != " "]
print("".join(nospace))

# 17. Characters appearing more than once
s = "programming"
dup = [i for i in s if s.count(i) > 1]
print(dup)

# 18. All words from sentences
sent = ["hello world", "python is easy"]
words = [w for s in sent for w in s.split()]
print(words)

# 19. Unique elements from list
lst = [1, 2, 2, 3, 4, 4]
uniq = [i for i in lst if lst.count(i) == 1]
print(uniq)

# 20. Cartesian product
a = [1, 2]
b = [3, 4]
pair = [(i, j) for i in a for j in b]
print(pair)



