# -*- coding: utf-8 -*-
"""Biz assigne 21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmCTTOBJGSONX-yrGsSr9-A_J38OIhcN
"""

# ---------------- LIST COMPREHENSION ----------------

# 1. Squares of numbers from 1 to 10
sq = [i*i for i in range(1, 11)]
print(sq)

# 2. Even numbers between 1 and 50
even = [i for i in range(1, 51) if i % 2 == 0]
print(even)

# 3. Convert strings to uppercase
names = ["abhi", "ram", "sham"]
up = [i.upper() for i in names]
print(up)

# 4. Only positive numbers
nums = [-3, 5, -1, 7, 0, 9]
pos = [i for i in nums if i > 0]
print(pos)

# 5. Tuples (num, num^2) from 1 to 5
tup = [(i, i*i) for i in range(1, 6)]
print(tup)

# 6. Extract vowels from string
s = "education"
v = [i for i in s if i in "aeiouAEIOU"]
print(v)

# 7. Flatten 2D list
lst = [[1, 2], [3, 4], [5, 6]]
flat = [j for i in lst for j in i]
print(flat)

# 8. Replace negative numbers with 0
nums = [-2, 4, -5, 6]
new = [0 if i < 0 else i for i in nums]
print(new)

# 9. Length of each word
words = ["python", "java", "c"]
lengths = [len(i) for i in words]
print(lengths)

# 10. Words not starting with A or a
words = ["Apple", "ball", "ant", "cat"]
res = [i for i in words if not i.lower().startswith('a')]
print(res)

# 11. Even or odd list
nums = [1, 2, 3, 4]
eo = ["even" if i % 2 == 0 else "odd" for i in nums]
print(eo)

# 12. Numbers divisible by 3 and 5 (1–100)
d35 = [i for i in range(1, 101) if i % 3 == 0 and i % 5 == 0]
print(d35)

# 13. Multiplication table 1–5
table = [[i*j for j in range(1, 6)] for i in range(1, 6)]
print(table)

# 14. Dictionary keys to list
d = {"a": 1, "b": 2}
keys = [i for i in d]
print(keys)

# 15. Digits from string
s = "ab12cd34"
digits = [i for i in s if i.isdigit()]
print(digits)

# 16. Remove spaces from string
s = "hello world"
nospace = [i for i in s if i != " "]
print("".join(nospace))

# 17. Characters appearing more than once
s = "programming"
dup = [i for i in s if s.count(i) > 1]
print(dup)

# 18. All words from sentences
sent = ["hello world", "python is easy"]
words = [w for s in sent for w in s.split()]
print(words)

# 19. Unique elements from list
lst = [1, 2, 2, 3, 4, 4]
uniq = [i for i in lst if lst.count(i) == 1]
print(uniq)

# 20. Cartesian product
a = [1, 2]
b = [3, 4]
pair = [(i, j) for i in a for j in b]
print(pair)


#lambda functions

# 21. Add two numbers
add = lambda x, y: x + y
print(add(3, 4))

# 22. Check even
iseven = lambda x: x % 2 == 0
print(iseven(6))

# 23. Last character of string
last = lambda s: s[-1]
print(last("python"))

# 24. Square numbers using map
nums = [1, 2, 3]
sq = list(map(lambda x: x*x, nums))
print(sq)

# 25. Odd numbers using filter
odd = list(filter(lambda x: x % 2 != 0, nums))
print(odd)

# 26. Sort tuples by second value
t = [(1, 3), (4, 1), (2, 2)]
print(sorted(t, key=lambda x: x[1]))

# 27. Palindrome check
pal = lambda s: s == s[::-1]
print(pal("madam"))

# 28. Max of three numbers
mx = lambda a, b, c: a if a > b and a > c else b if b > c else c
print(mx(3, 9, 5))

# 29. Reverse string
rev = lambda s: s[::-1]
print(rev("hello"))

# 30. String to int using map
nums = list(map(lambda x: int(x), ["1", "2", "3"]))
print(nums)

# 31. Remove empty strings
lst = ["hi", " ", "bye", ""]
clean = list(filter(lambda x: x != "", lst))
print(clean)

# 32. Larger of two numbers
big = lambda a, b: a if a > b else b
print(big(4, 9))

# 33. Divisible by 5
d5 = lambda x: x % 5 == 0
print(d5(20))

# 34. Add 10 to each element
nums = [1, 2, 3]
plus10 = list(map(lambda x: x + 10, nums))
print(plus10)

# 35. Sort list of dict by age
data = [{"age": 25}, {"age": 20}]
print(sorted(data, key=lambda x: x["age"]))

# 36. Check vowel
vowel = lambda c: c.lower() in "aeiou"
print(vowel("a"))

# 37. Words length > 5
words = ["python", "java", "programming"]
long = list(filter(lambda x: len(x) > 5, words))
print(long)

# 38. Area of circle
area = lambda r: math.pi * r * r
print(area(5))

# 39. Remove duplicates
lst = [1, 2, 2, 3]
nodup = list(filter(lambda x: lst.count(x) == 1, lst))
print(nodup)

# 40. Product of list
nums = [1, 2, 3, 4]
prod = reduce(lambda a, b: a*b, nums)
print(prod)

# 41. Absolute value
ab = lambda x: x if x >= 0 else -x
print(ab(-7))

# 42. Sort strings by length
s = ["hi", "hello", "bye"]
print(sorted(s, key=lambda x: len(x)))

# 43. Uppercase characters from string
s = "PyThOn"
up = list(filter(lambda x: x.isupper(), s))
print(up)

# 44. Square if even, cube if odd
cal = lambda x: x*x if x % 2 == 0 else x*x*x
print(cal(3))

# 46. Celsius to Fahrenheit
c2f = lambda c: (c * 9/5) + 32
print(c2f(30))

# 47. Anagram check
ana = lambda a, b: sorted(a) == sorted(b)
print(ana("listen", "silent"))

# 48. Numeric values from mixed list
mix = [1, "a", 3, "b"]
num = list(filter(lambda x: type(x) == int, mix))
print(num)

# 49. Any negative number
nums = [1, -2, 3]
print(any(map(lambda x: x < 0, nums)))

# 50. Lambda returning multiplier function
mul = lambda b: lambda x: x * b
f = mul(5)
print(f(10))

